### ISSUE TITLE
Update from 1.0.1 to 1.0.2 isnt possible

### ISSUE THREAD

**Issue by syntafin** [IsekaiDevPlugins/de.isekaidev.discord.wbbBridge#2]
Following error appear:

```
An update of package de.isekaidev.discord.wbbBridge from version 1.0.1 to 1.0.2 is not supported.

Stacktrace:
#0 /var/www/vhosts/double-spoiler.de/httpdocs/forum/wcf/lib/system/package/PackageInstallationScheduler.class.php(516): wcf\system\package\PackageInstallationScheduler->findShortestUpdateThread('de.isekaidev.di...', Array, '1.0.1', '1.0.2')
#1 /var/www/vhosts/double-spoiler.de/httpdocs/forum/wcf/lib/system/package/PackageInstallationScheduler.class.php(104): wcf\system\package\PackageInstallationScheduler->updatePackage(50, '1.0.2')
#2 /var/www/vhosts/double-spoiler.de/httpdocs/forum/wcf/lib/system/package/PackageInstallationScheduler.class.php(65): wcf\system\package\PackageInstallationScheduler->tryToInstallPackage(Object(wcf\data\package\Package), '1.0.2', true, false)
#3 /var/www/vhosts/double-spoiler.de/httpdocs/forum/wcf/lib/data/package/update/PackageUpdateAction.class.php(520): wcf\system\package\PackageInstallationScheduler->buildPackageInstallationStack(false)
#4 /var/www/vhosts/double-spoiler.de/httpdocs/forum/wcf/lib/data/package/update/PackageUpdateAction.class.php(472): wcf\data\package\update\PackageUpdateAction->createQueue('update')
#5 [internal function]: wcf\data\package\update\PackageUpdateAction->prepareUpdate()
#6 /var/www/vhosts/double-spoiler.de/httpdocs/forum/wcf/lib/data/AbstractDatabaseObjectAction.class.php(204): call_user_func(Array)
#7 /var/www/vhosts/double-spoiler.de/httpdocs/forum/wcf/lib/action/AJAXProxyAction.class.php(74): wcf\data\AbstractDatabaseObjectAction->executeAction()
#8 /var/www/vhosts/double-spoiler.de/httpdocs/forum/wcf/lib/action/AJAXInvokeAction.class.php(104): wcf\action\AJAXProxyAction->invoke()
#9 /var/www/vhosts/double-spoiler.de/httpdocs/forum/wcf/lib/action/AbstractAction.class.php(47): wcf\action\AJAXInvokeAction->execute()
#10 /var/www/vhosts/double-spoiler.de/httpdocs/forum/wcf/lib/action/AJAXInvokeAction.class.php(63): wcf\action\AbstractAction->__run()
#11 /var/www/vhosts/double-spoiler.de/httpdocs/forum/wcf/lib/system/request/Request.class.php(83): wcf\action\AJAXInvokeAction->__run()
#12 /var/www/vhosts/double-spoiler.de/httpdocs/forum/wcf/lib/system/request/RequestHandler.class.php(94): wcf\system\request\Request->execute()
#13 /var/www/vhosts/double-spoiler.de/httpdocs/forum/wcf/acp/index.php(9): wcf\system\request\RequestHandler->handle('wcf', true)
#14 {main}
```

**Comment by Akizo96** [comment]
Hey, already notice that. As i just changed the package.xml and put the exclude for a package in it, i forgot to add the update section. Will change it with the next update.
